{
 "title": "Dojot - 100k",
 "time": { "from": "2019-11-21T14:00:27.000Z", "to": "2019-11-21T15:30:27.000Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   { "name": "namespace", "label": "namespace" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(socket_open - socket_close)",
     "legendFormat": "Online"
    },
    {
     "expr": "sum(queue_processes) - sum(socket_open - socket_close)",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Pods - AVG -   (time (ms) between locust and kafka )  ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "Dojot_Statistics{kind=\"avg\"}"
    },
    {}
   ]
  },
  {
   "title": "Pods -  (Standard Deviation)  ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "Dojot_Statistics{kind=\"median\"}"
    }
   ]
  },
  { "title": "VerneMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Current MQTT Receive rate",
   "type": "singlestat",
   "description": "Current rate per second of received MQTT PUBLISH frames by the broker.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_received[30s]))"
    }
   ]
  },
  {
   "title": "MQTT Connect Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_connect_received[1m]))",
     "legendFormat": "Connect"
    },
    {
     "expr": "sum(rate(mqtt_connack_sent[1m]))",
     "legendFormat": "Connack"
    }
   ]
  },
  {
   "title": "MQTT Publish Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_publish_received[1m]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(rate(mqtt_publish_sent[1m]))",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Queue Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_message_unhandled[1m]))",
     "legendFormat": "Unhandled"
    }
   ]
  },
  {
   "title": "Connect/Disconnect Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "rate(socket_open[30s])", "legendFormat": "Connect (Socket Open)" },
    { "expr": "rate(socket_close[30s])", "legendFormat": "Disconnect (Socket Close)" }
   ]
  },
  {
   "title": "QOS 0,1,2: PUBLISH Received, Sent & Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mqtt_publish_received[30s])",
     "legendFormat": "PUBLISH Received"
    },
    { "expr": "rate(mqtt_publish_sent[30s])", "legendFormat": "PUBLISH Sent" },
    { "expr": "rate(mqtt_publish_error[30s])", "legendFormat": "PUBLISH Error" },
    { "expr": "mqtt_publish_auth_error", "legendFormat": "PUBLISH Auth Error" }
   ]
  },
  {
   "title": "MQTT CONNACK",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mqtt_connect_received[30s])",
     "legendFormat": "MQTT CONNECT Received"
    },
    {
     "expr": "rate(mqtt_connack_accepted_sent[30s])",
     "legendFormat": "MQTT CONNACK sent"
    }
   ]
  },
  {
   "title": "MQTT CONNACK Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mqtt_connack_bad_credentials_sent[30s])",
     "legendFormat": "Connack Bad Credentials"
    },
    {
     "expr": "rate(mqtt_connack_identifier_rejected_sent[30s])",
     "legendFormat": "Connack ID rejected"
    },
    {
     "expr": "rate(mqtt_connack_not_authorized_sent[30s])",
     "legendFormat": "Connack Not Authorized"
    },
    {
     "expr": "rate(mqtt_connack_server_unavailable_sent[30s])",
     "legendFormat": "Connack Server Unavailable"
    },
    {
     "expr": "rate(mqtt_connack_unacceptable_protocol_sent[30s])",
     "legendFormat": "Connack Unacceptable Protocol"
    }
   ]
  },
  {
   "title": "Messages in Queues",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(queue_message_in[1m])", "legendFormat": "In" },
    { "expr": "rate(queue_message_out[1m])", "legendFormat": "Out" },
    { "expr": "rate(queue_message_drop[1m])", "legendFormat": "Dropped" },
    {
     "expr": "rate(queue_message_unhandled[1m])",
     "legendFormat": "Unhandled"
    }
   ]
  },
  {
   "title": "Current Queue Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "queue_processes", "legendFormat": "Queue Total" }
   ]
  },
  { "title": "Service Dojot Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Pods -  Median - (time (ms) between locust and kafka)  ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "Dojot_Statistics{kind=\"median\"}"
    }
   ]
  },
  {
   "title": "Cluster - Avg (time (ms) between locust and kafka)  ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(Dojot_Statistics) by (avg) "
    }
   ]
  }
 ]
}